// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpUOTYpfyAs3mSZNsR8i4jcydBupNhWR8-sb6GSrLdI',
    appId: '1:940122865669:android:144a2f4af4c1ae63101c6c',
    messagingSenderId: '940122865669',
    projectId: 'facebook-login-9426d',
    storageBucket: 'facebook-login-9426d.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDi5RBqMRgwJhKEvzPowtNBBZMz5wunkos',
  //   appId: '1:921291927243:ios:d2841c51086f69c79fb54e',
  //   messagingSenderId: '921291927243',
  //   projectId: 'mkseiko-washwalletapp',
  //   storageBucket: 'mkseiko-washwalletapp.appspot.com',
  //   iosBundleId: 'com.mkseiko.washwalletdev',
  // );
}
